# Generated by Django 6.0.4 on 2026-05-13 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_evento', models.CharField(choices=[('Boda', 'Boda'), ('Cumpleaños', 'Cumpleaños'), ('Grado', 'Grado'), ('Quinceañera', 'Quinceañera'), ('BabyShower', 'Baby Shower'), ('FiestaInfantil', 'Fiesta Infantil'), ('Despedida', 'Despedida'), ('Aniversario', 'Aniversario'), ('EventoCorporativo', 'Evento Corporativo')], max_length=50)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('num_personas', models.IntegerField(default=0)),
                ('presupuesto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('planificando', 'Planificando'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversacion', models.ForeignKey(blank=True, db_column='conversacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conversacion')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'eventos',
                'managed': True,
            },
        ),
    ]
